# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# https://stackoverflow.com/questions/64935598/git-pre-commit-get-all-python-files
default_language_version:
  python: python3.10
default_stages:
  - commit
  - push
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # https://github.com/pre-commit/pre-commit-hooks#check-ast
      - description: Simply checks whether the files parse as valid python.
        id: check-ast
        types:
          - python

      # https://github.com/pre-commit/pre-commit-hooks#check-added-large-files
      - description: prevents giant files from being committed.
        id: check-added-large-files

      # https://github.com/pre-commit/pre-commit-hooks#check-json
      - description: Checks json files for parseable syntax.
        id: check-json
        types:
          - json

      # https://github.com/pre-commit/pre-commit-hooks#check-toml
      - description: Checks toml files for parseable syntax.
        id: check-toml
        types:
          - toml

      # https://github.com/pre-commit/pre-commit-hooks#check-toml
      - description: Checks yaml files for parseable syntax.
        id: check-yaml
        types:
          - yaml

      # https://github.com/pre-commit/pre-commit-hooks#end-of-file-fixer
      - description: Ensures that a file is either empty, or ends with one newline.
        id: end-of-file-fixer

      # https://github.com/pre-commit/pre-commit-hooks#trailing-whitespace
      - description: Trims trailing whitespace.
        id: trailing-whitespace

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.28.0
    hooks:
      - id: commitizen
